// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MergePDFs(arg1, arg2) {
  return window['go']['main']['App']['MergePDFs'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectOutputFile() {
  return window['go']['main']['App']['SelectOutputFile']();
}

export function SelectPDFs(arg1) {
  return window['go']['main']['App']['SelectPDFs'](arg1);
}

export function SplitPDF(arg1, arg2) {
  return window['go']['main']['App']['SplitPDF'](arg1, arg2);
}

export function TrimPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['TrimPDF'](arg1, arg2, arg3);
}
