// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MergePDFs(arg1:Array<string>,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectOutputFile():Promise<string>;

export function SelectPDFs(arg1:boolean):Promise<Array<string>>;

export function SplitPDF(arg1:string,arg2:string):Promise<string>;

export function TrimPDF(arg1:string,arg2:string,arg3:string):Promise<string>;
